#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gc_seqdiff.py — GC sequential-diff harness (Phase 7, DELIV-8a).

Task: .pge/tasks/task-gc-seqdiff.md; authoritative design:
docs/kernel-fuzzing-design.md §7.2 (sequential diff = the GC logic
correctness main oracle) + §7.0 (workload x oracle matrix).

For each W-pure workload P (generated by gc_workloads.py --kind pure):

    assert output(`tinyactor run P`) == output(`TA_GC_STRESS=N tinyactor run P`)

byte-for-byte.  W-pure is strictly single-actor with no send/spawn
(gated by gc_workloads.assert_no_messaging), so both runs are
sequentially deterministic and directly comparable (§7.0 premise).
Any difference is a finding — including the known GC bug #8
(val_deep_copy missing root, .pge/findings/gcstress-val-deep-copy-
missing-root.md), which this oracle is DESIGNED to expose; findings are
recorded, never fixed here.

Classification (closed enum):
    pass      both sides exit 0 and stdout bytes are identical
    mismatch  both sides exit 0 but stdout differs (byte-level)
    crash     either side exits nonzero / dies by signal
    timeout   either side exceeds --timeout (runner timeout convention)

Findings are persisted under .pge/findings/seqdiff/<category>-<sig8>/
(morph.py §5.4 conventions: signature = category + sha256 of
whitespace-stripped source, first 16 hex; per-finding src + both-side
stdout/stderr/exit + run.sh repro + meta.json).  Signature dedup: in
memory per run and reloaded from the findings tree on start, so
re-running over the same window skips re-recording — but NOT the exit
code: while any non-pass result stands the exit is 1 (CI stays red).

CLI:
    python3 tools/kernfuzz/gc_seqdiff.py --seeds 10000:10200 \
        [--stress-n 1[,2]] [--jobs J] [--timeout 10] [--out DIR] [--json]

Exit codes: 0 = every seed pair byte-identical; 1 = at least one
non-pass result (mismatch/crash/timeout, counted whether newly
recorded or dedup-skipped, for CI wire-up); 2 = tooling skip
(./tinyactor missing).
Stdlib only (DEC-6).
"""

import argparse
import concurrent.futures
import hashlib
import json
import os
import subprocess
import sys
import tempfile

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import gc_workloads               # noqa: E402  (generate + W-pure gate)

_REPO = os.path.normpath(os.path.join(_HERE, "..", ".."))
TINYACTOR = os.path.join(_REPO, "tinyactor")

DEFAULT_OUT = os.path.join(_REPO, ".pge", "findings", "seqdiff")
# Timeout budget.  The runner fast-ring convention is 10s, but the STRESS
# side amplifies run time enormously (TA_GC_STRESS=1 forces a full
# semispace copy per allocation; .pge/findings/gcstress-val-deep-copy-
# missing-root.md measures up to ~250x on compile-heavy work).  A W-pure
# seed that runs in 0.1s normal can take ~4s+ at N=1 standalone, and more
# under parallel load — 10s produces contention-artifact "timeout"
# findings, not real hangs.  Default is therefore 60s; pass --timeout 10
# only for normal-side experiments.
DEFAULT_TIMEOUT = 60

CATEGORIES = ("mismatch", "crash", "timeout")

# ---------------------------------------------------------------------------
# execution
# ---------------------------------------------------------------------------


class RunRes(object):
    """One side's run result (mirrors morph.py RunRes field style)."""

    __slots__ = ("rc", "out", "err", "timed_out")

    def __init__(self, rc, out, err, timed_out):
        self.rc = rc
        self.out = out
        self.err = err
        self.timed_out = timed_out


def run_side(binary, src_path, stress_n, timeout):
    """Run `binary run src_path` with TA_GC_STRESS unset (0) or =stress_n.

    Returns RunRes; timed_out=True when the subprocess exceeded timeout
    (subprocess.TimeoutExpired — child is killed by subprocess.run).
    """
    env = dict(os.environ)
    if stress_n:
        env["TA_GC_STRESS"] = str(stress_n)
    else:
        env.pop("TA_GC_STRESS", None)
    try:
        proc = subprocess.run(
            [binary, "run", src_path],
            capture_output=True, timeout=timeout, env=env)
        return RunRes(proc.returncode, proc.stdout, proc.stderr, False)
    except subprocess.TimeoutExpired as e:
        return RunRes(None, e.stdout or b"", e.stderr or b"", True)


def run_program(binary, src_text, stress_n, timeout):
    """Write src to a temp .ta file and run the given side on it."""
    fd, path = tempfile.mkstemp(suffix=".ta", prefix="seqdiff_")
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(src_text.encode("utf-8"))
        return run_side(binary, path, stress_n, timeout)
    finally:
        os.unlink(path)


# ---------------------------------------------------------------------------
# classification / signature (morph.py §5.4 conventions)
# ---------------------------------------------------------------------------


def strip_ws_sha16(text):
    """sha256 of the whitespace-stripped source, first 16 hex chars."""
    stripped = "".join(text.split()).encode("utf-8")
    return hashlib.sha256(stripped).hexdigest()[:16]


def signature(category, src_text):
    """signature = (类别, sha256(strip_ws(源码)) 前 16 hex)."""
    return "%s:%s" % (category, strip_ws_sha16(src_text))


def classify(normal, stress):
    """Classify one (normal, stress) run pair. Returns category string.

    Order matters: a timeout on either side masks the comparison (we
    cannot distinguish 'output would have differed' from 'output was
    truncated'), then crash on either side, then byte compare.
    """
    if normal.timed_out or stress.timed_out:
        return "timeout"
    if normal.rc != 0 or stress.rc != 0:
        return "crash"
    if normal.out != stress.out:
        return "mismatch"
    return "pass"


# ---------------------------------------------------------------------------
# findings persistence (morph.py conventions, adapted)
# ---------------------------------------------------------------------------


def load_known_signatures(out_dir):
    """Reload signatures recorded by previous runs for dedup."""
    known = set()
    if not os.path.isdir(out_dir):
        return known
    for name in sorted(os.listdir(out_dir)):
        meta = os.path.join(out_dir, name, "meta.json")
        if not os.path.isfile(meta):
            continue
        try:
            with open(meta, "r", encoding="utf-8") as f:
                m = json.load(f)
            known.add(m["signature"])
        except (ValueError, KeyError, OSError):
            continue
    return known


def record_finding(out_dir, category, seed, stress_n, src_text,
                   normal, stress, dedup):
    """Persist one finding dir; dedup by signature. Returns True if new.

    Layout: <out>/<category>-<sig8>/ with src.ta, per-side
    stdout/stderr/exit files, run.sh repro, meta.json.
    """
    sig = signature(category, src_text)
    if sig in dedup:
                return False
    dedup.add(sig)
    sig_hash = sig.split(":", 1)[1]
    fdir = os.path.join(out_dir, "%s-%s" % (category, sig_hash[:8]))
    os.makedirs(fdir, exist_ok=True)

    def _w(name, data):
        with open(os.path.join(fdir, name), "wb") as f:
            f.write(data if isinstance(data, bytes) else data.encode("utf-8"))

    _w("src.ta", src_text)
    for tag, res in (("normal", normal), ("stress", stress)):
        _w("stdout_%s.txt" % tag, res.out)
        _w("stderr_%s.txt" % tag, res.err)
        _w("exit_%s.txt" % tag,
           "TIMEOUT" if res.timed_out else str(res.rc))
    _w("meta.json", json.dumps({
        "tool": "gc_seqdiff",
        "category": category,
        "signature": sig,
        "seed": seed,
        "stress_n": stress_n,
        "kind": "W-pure",
        "oracle": "sequential diff (design §7.2): unset vs TA_GC_STRESS=%d"
                  % stress_n,
    }, indent=2, sort_keys=True) + "\n")

    repro = ["#!/bin/sh",
             "# gc_seqdiff finding repro - category=%s signature=%s"
             % (category, sig),
             "# kind=W-pure seed=%d stress_n=%d" % (seed, stress_n),
             "set -e",
             "cd %s" % _REPO,
             "./tinyactor run %s" % os.path.join(fdir, "src.ta"),
             "TA_GC_STRESS=%d ./tinyactor run %s"
             % (stress_n, os.path.join(fdir, "src.ta"))]
    run_sh = os.path.join(fdir, "run.sh")
    with open(run_sh, "w", encoding="utf-8") as f:
        f.write("\n".join(repro) + "\n")
    os.chmod(run_sh, 0o755)
    return True


# ---------------------------------------------------------------------------
# per-seed driver
# ---------------------------------------------------------------------------


def check_seed(binary, seed, stress_n, timeout):
    """Generate + run + classify one seed. Returns a result dict.

    Pure function over (binary, seed, stress_n, timeout): performs the
    subprocess runs but no filesystem side effects, so it is safe to
    call from worker threads.
    """
    src_text = gc_workloads.generate("pure", seed)
    gc_workloads.assert_no_messaging(src_text)   # defensive §7.0 re-gate
    normal = run_program(binary, src_text, 0, timeout)
    stress = run_program(binary, src_text, stress_n, timeout)
    return {
        "seed": seed,
        "category": classify(normal, stress),
        "src_text": src_text,
        "normal": normal,
        "stress": stress,
    }


def parse_seeds(spec):
    """Parse 'A:B' into range(A, B); reject malformed/bad windows."""
    parts = spec.split(":")
    if len(parts) != 2:
        raise ValueError("--seeds must be A:B, got %r" % spec)
    a, b = int(parts[0]), int(parts[1])
    if b <= a:
        raise ValueError("--seeds window must be non-empty (A < B)")
    return list(range(a, b))


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="GC sequential diff harness: W-pure normal vs "
                    "TA_GC_STRESS=N, byte-level compare "
                    "(docs/kernel-fuzzing-design.md §7.2)")
    ap.add_argument("--seeds", required=True, metavar="A:B",
                    help="half-open seed window, e.g. 10000:10200")
    ap.add_argument("--stress-n", default="1",
                    help="GC stress level(s) to diff against normal; "
                         "single int or comma list, e.g. '1' or '1,2' "
                         "(default 1)")
    ap.add_argument("--jobs", type=int, default=1,
                    help="parallel workers (subprocess-bound, safe)")
    ap.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT,
                    help="per-run timeout seconds (default %d)"
                         % DEFAULT_TIMEOUT)
    ap.add_argument("--out", default=DEFAULT_OUT,
                    help="findings directory (default .pge/findings/seqdiff)")
    ap.add_argument("--json", action="store_true",
                    help="emit machine-readable summary JSON on stdout")
    args = ap.parse_args(argv)

    stress_ns = [int(x) for x in str(args.stress_n).split(",")]
    if not stress_ns or any(n < 1 for n in stress_ns):
        ap.error("--stress-n must be int(s) >= 1")
    seeds = parse_seeds(args.seeds)

    if not os.path.exists(TINYACTOR):
        print("gc-seqdiff-SKIPPED: %s not built" % TINYACTOR,
              file=sys.stderr)
        return 2

    dedup = load_known_signatures(args.out)
    counts = dict((c, 0) for c in CATEGORIES)
    counts["pass"] = 0
    counts["dedup-skip"] = 0
    findings = []

    def work(item):
        seed, n = item
        return n, check_seed(TINYACTOR, seed, n, args.timeout)

    tasks = [(s, n) for s in seeds for n in stress_ns]
    if args.jobs > 1:
        with concurrent.futures.ThreadPoolExecutor(
                max_workers=args.jobs) as ex:
            results = list(ex.map(work, tasks))
    else:
        results = [work(t) for t in tasks]

    for stress_n, res in results:
        counts[res["category"]] += 1
        if res["category"] == "pass":
            continue
        new = record_finding(
            args.out, res["category"], res["seed"], stress_n,
            res["src_text"], res["normal"], res["stress"], dedup)
        if new:
            findings.append((res["category"], res["seed"], stress_n,
                             res["src_text"]))
        else:
            counts["dedup-skip"] += 1

    summary = {
        "tool": "gc_seqdiff",
        "seeds_window": args.seeds,
        "stress_n": stress_ns,
        "total": len(tasks),
        "counts": counts,
        "new_findings": [
            {"category": c, "seed": s, "stress_n": n,
             "signature": signature(c, t)} for (c, s, n, t) in findings],
    }
    if args.json:
        print(json.dumps(summary, indent=2))
    else:
        print("gc-seqdiff: %s  stress_n=%s  total=%d  pass=%d "
              "mismatch=%d crash=%d timeout=%d dedup-skip=%d "
              "new_findings=%d"
              % (args.seeds, ",".join(str(n) for n in stress_ns),
                 summary["total"], counts["pass"], counts["mismatch"],
                 counts["crash"], counts["timeout"],
                 counts["dedup-skip"], len(findings)))
        for (c, s, n, t) in findings:
            print("  FINDING %s seed=%d stress_n=%d sig=%s"
                  % (c, s, n, signature(c, t)))
        print("findings dir: %s" % args.out)
    return 1 if (counts["mismatch"] or counts["crash"]
                 or counts["timeout"]) else 0


if __name__ == "__main__":
    sys.exit(main())