#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gc_workloads.py — three GC-hostile TA workload generators (Phase 7).

Task: .pge/tasks/task-workloads.md; authoritative design:
docs/kernel-fuzzing-design.md §7.0-7.4 (workload x oracle matrix) + DEC-6
(Python3 stdlib only).

Each generated workload strictly serves ONE oracle (§7.0):

  kind    form                                          feeds
  ------  --------------------------------------------  ----------------------
  pure    single actor, pure allocation (closure        GC sequential diff
          capture-and-discard, deep shared structures,  (§7.2: stress vs
          string churn).  STRICTLY no send/spawn/       normal, compare())
          monitor/recv/receive/self — the generator
          gates the emitted text (§7.0: sequential
          determinism premise).
  msg     multi-actor message churn, deep structures    multiset harness (§7.3)
          inside send payloads; output is one line per
          message "<wid> <seq>" (sorting happens in the
          harness, never in TA).  spawn is zero-arg
          (R3): worker parameters travel as the FIRST
          message, worker recv()s the config before
          entering its work loop.
  chaos   high-frequency spawn/death + message mix;     TSan long-run + timeout
          short-lived processes; per-round output is    detection (§7.4)
          one deterministic line, so a hang shows up
          as a missing line instead of garbled output.

Common:
  * seeded PRNG from tools/kernfuzz/prng.py (M-2, never stdlib random);
    same --seed -> byte-identical program, byte-identical W-pure output.
  * CLI: --kind pure|msg|chaos --seed S --scale N  -> .ta source on stdout.
    --smoke additionally build+runs the generated program via ./tinyactor
    and exits nonzero on failure (generator self-check).
  * TA language gotchas honored (AGENTS.md / kernfuzz gen.py R-rules):
    bool predicates used bare in `if` (no `== 1`), str.concat takes exactly
    2 args, negative int literals rendered as (0 - N) (no unary minus),
    all integer literals within int48.

Language forms used here were probed against the working-tree
parser/typecheck/VM before this generator was written (see
.pge/progress.md task-workloads): tail-recursive list build, non-tail
tree recursion (depth-bounded), closure capture-and-discard,
spawn('name) + first-message config, monitor/recv DOWN barrier, divzero
actor crash (kills only the crashing actor; monitor still delivers DOWN).
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import prng                      # noqa: E402

_REPO = os.path.normpath(os.path.join(_HERE, "..", ".."))
TINYACTOR = os.path.join(_REPO, "tinyactor")

KINDS = ("pure", "msg", "chaos")

# Gate for W-pure (§7.0: "W-pure 严格不含 send/spawn"): no actor primitive
# may appear anywhere in the emitted text, including comments.
PURE_BANNED_RE = re.compile(r"\b(send|spawn|monitor|recv|receive|self)\b")


def assert_no_messaging(text):
    """W-pure gate: raise ValueError if any actor primitive appears.

    This is the load-side guard for the §7.2 sequential-diff oracle: a
    single actor with no messaging keeps normal vs TA_GC_STRESS runs
    deterministic and line-comparable.
    """
    m = PURE_BANNED_RE.search(text)
    if m:
        raise ValueError(
            "W-pure workload must not contain actor primitive %r (§7.0)"
            % m.group(0))


def _check_scale(scale):
    if scale < 1:
        raise ValueError("scale must be >= 1")
    if scale > 1000000:
        raise ValueError("scale must be <= 1000000")
    return scale


def _header(kind, seed, scale, note):
    """Traceability comment. Never contains words banned for W-pure."""
    return ("// gc_workloads %s seed=%d scale=%d %s\n"
            "// generated by tools/kernfuzz/gc_workloads.py — do not edit\n"
            % (kind, seed, scale, note))


# ---------------------------------------------------------------------------
# W-pure: single actor, pure allocation (§7.2 sequential diff)
# ---------------------------------------------------------------------------

def gen_pure(seed, scale):
    """Emit a W-pure workload: deterministic checksum-per-phase program.

    Phases (order seed-chosen; every count seed-jittered and scaled):
      closure  capture-and-discard closures, called once each
      list     deep list build (tail-recursive) + full traversal
      share    short fresh spine consed onto ONE long shared base list
               K times — GC must keep the shared tail alive per spine
      tree     depth-bounded binary tree build + recursive traversal
      str      string churn (fresh str.concat + str.from_int garbage)

    Output: one labeled checksum line per phase.  Deterministic: no
    messaging, no time, no scheduler involvement — so `tavm run` vs
    `TA_GC_STRESS=1 tavm run` must be byte-identical (§7.2).
    """
    _check_scale(scale)
    p = prng.make_prng(seed)

    n_closure = 2000 * scale + p.next_range(500)
    n_list = 20000 * scale + p.next_range(2000)
    share_base_n = 500 + p.next_range(50)
    share_k = 200 * scale + p.next_range(100)
    tree_depth = 8 + p.next_range(5)          # 2^depth nodes, bounded
    n_str = 2000 * scale + p.next_range(500)
    closure_arg = 2 + p.next_range(8)
    filler = chr(97 + p.next_range(26))
    labels = ["closure", "list", "share", "tree", "str"]
    # seeded phase order (stable shuffle via Fisher-Yates on prng draws)
    for i in range(len(labels) - 1, 0, -1):
        j = p.next_range(i + 1)
        labels[i], labels[j] = labels[j], labels[i]

    lines = [_header("W-pure", seed, scale,
                     "single actor / pure allocation / sequential diff")]
    lines.append("import str\n")

    lines.append("""\
fn make_adder(n) {
  fn(x) { x + n }
}

fn closure_churn(n, acc) {
  if n == 0 {
    acc
  } else {
    let f = make_adder(n)
    closure_churn(n - 1, acc + f(%d))
  }
}
""" % closure_arg)

    lines.append("""\
fn build(n, acc) {
  if n == 0 {
    acc
  } else {
    build(n - 1, cons(n, acc))
  }
}

fn sum_list(lst, acc) {
  if null?(lst) {
    acc
  } else {
    sum_list(cdr(lst), acc + car(lst))
  }
}
""")

    lines.append("""\
// fresh 2-cell spine sharing ONE base list as tail; base must survive
// every spine sum or the checksum changes (shared-structure GC trap)
fn share(base, k, acc) {
  if k == 0 {
    acc
  } else {
    let l = cons(0 - 1, cons(0 - 2, base))
    share(base, k - 1, acc + sum_list(l, 0))
  }
}
""")

    lines.append("""\
fn tree(d) {
  if d == 0 {
    1
  } else {
    cons(tree(d - 1), cons(tree(d - 1), nil))
  }
}

fn tree_sum(t) {
  if pair?(t) {
    tree_sum(car(t)) + tree_sum(car(cdr(t)))
  } else {
    t
  }
}
""")

    lines.append("""\
fn strchurn(n, c, acc) {
  if n == 0 {
    acc
  } else {
    let s = str.concat(str.from_int(n), c)
    strchurn(n - 1, c, acc + str.length(s))
  }
}
""")

    # main: phase bodies emitted in the seeded order, each printing one
    # labeled checksum line (every print on its own line)
    lines.append("fn main() {")
    for name in labels:
        if name == "closure":
            lines.append("  print(str.concat(\"closure \","
                         " str.from_int(closure_churn(%d, 0))))"
                         % n_closure)
        elif name == "list":
            lines.append("  let lst = build(%d, nil)" % n_list)
            lines.append("  print(str.concat(\"list \","
                         " str.from_int(sum_list(lst, 0))))")
        elif name == "share":
            lines.append("  let base = build(%d, nil)" % share_base_n)
            lines.append("  print(str.concat(\"share \","
                         " str.from_int(share(base, %d, 0))))" % share_k)
        elif name == "tree":
            lines.append("  print(str.concat(\"tree \","
                         " str.from_int(tree_sum(tree(%d)))))" % tree_depth)
        elif name == "str":
            lines.append("  print(str.concat(\"str \","
                         " str.from_int(strchurn(%d, \"%s\", 0))))"
                         % (n_str, filler))
    lines.append("}\n")
    text = "\n".join(lines)
    assert_no_messaging(text)
    return text


# ---------------------------------------------------------------------------
# W-msg: multi-actor message churn (§7.3 multiset harness)
# ---------------------------------------------------------------------------

def gen_msg(seed, scale):
    """Emit a W-msg workload: K workers x M messages -> "<wid> <seq>" lines.

    First-message configuration pattern (R3: spawn is zero-arg ONLY):
      spawn('worker); send(w, [cp, wid, m, plen])  ->  worker recv()s it.
    The collector likewise gets [K*M] as its first message, and main ends
    with monitor(cp) + recv() so the program terminates only after the
    collector has drained every message.

    Each message payload embeds a freshly built deep list (plen cons
    cells); send deep-copies it and the collector drops it — deep-structure
    churn across send boundaries, the §7.3 "跨 send 共享/深结构载荷" shape.
    Output is exactly K*M lines "<wid> <seq>", unsorted (the harness sorts).
    """
    _check_scale(scale)
    p = prng.make_prng(seed)

    k = min(16, 2 + scale) + p.next_range(2)
    m = 25 * scale + p.next_range(10)
    base_plen = 50 + p.next_range(50)
    total = k * m

    lines = [_header("W-msg", seed, scale,
                     "K=%d M=%d plen_base=%d" % (k, m, base_plen))]
    lines.append("import str\n")

    lines.append("""\
fn collect_loop(i, n) {
  if i == n {
    0
  } else {
    let msg = recv()
    print(str.concat(str.from_int(car(msg)), str.concat(" ", str.from_int(car(cdr(msg))))))
    collect_loop(i + 1, n)
  }
}

// collector: first message = [total]; then drain total messages,
// printing one "<wid> <seq>" line each (no sorting in TA)
fn collector() {
  let cfg = recv()
  collect_loop(0, car(cfg))
}
""")

    lines.append("""\
// fresh deep payload per message: send deep-copies it, collector drops it
fn payload(n, acc) {
  if n == 0 {
    acc
  } else {
    payload(n - 1, cons(n, acc))
  }
}

fn wloop(cp, wid, s, m, plen) {
  if s == m {
    0
  } else {
    send(cp, cons(wid, cons(s, payload(plen, nil))))
    wloop(cp, wid, s + 1, m, plen)
  }
}

// worker: first message = [cp, wid, m, plen] (spawn is zero-arg, R3)
fn worker() {
  let cfg = recv()
  wloop(car(cfg), car(cdr(cfg)), 0, car(cdr(cdr(cfg))), car(cdr(cdr(cdr(cfg)))))
}
""")

    lines.append("fn main() {")
    lines.append("  let cp = spawn('collector)")
    lines.append("  send(cp, cons(%d, nil))" % total)
    for wid in range(k):
        plen = base_plen + p.next_range(10 * scale + 10)
        lines.append("  let w%d = spawn('worker)" % wid)
        lines.append("  send(w%d, cons(cp, cons(%d, cons(%d, cons(%d, nil)))))"
                     % (wid, wid, m, plen))
    lines.append("  let ref = monitor(cp)")
    lines.append("  recv()")
    lines.append("}\n")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# W-chaos: spawn/death high frequency (§7.4 TSan long-run)
# ---------------------------------------------------------------------------

def gen_chaos(seed, scale):
    """Emit a W-chaos workload: R rounds x C short-lived leaves per round.

    Per round main spawns C leaves, monitors each, waits for exactly C
    DOWN messages, then prints one "round <r>" line.  Leaf behaviors are
    seed-chosen per slot from a config table (first message):
      alloc n  — build-and-discard an n-cell list (alloc churn)
      sub      — spawn one nested child and wait for its DOWN
      die      — die by divzero crash (exercises the crash/death path;
                 monitor still delivers DOWN, other actors unaffected —
                 probed before use, see .pge/progress.md task-workloads)

    Output: one deterministic line per round + a final "done <R>" line —
    a TSan hang/deadlock shows up as missing lines / timeout, not garbled
    text.  Scale R for 30min-class long runs (§7.4 nightly).
    """
    _check_scale(scale)
    p = prng.make_prng(seed)

    rounds = 50 * scale + p.next_range(10)
    c = min(32, 4 + p.next_range(4))
    # per-slot leaf configs: [alloc_n, sub?, die?] — at least one slot
    # dies and one spawns a sub-child per round when C >= 2
    slots = []
    for j in range(c):
        alloc_n = 50 + p.next_range(451)
        sub = (j % 3 == 1)
        die = (j % 4 == 3)
        slots.append((alloc_n, sub, die))
    if c >= 2 and not any(d for (_, _, d) in slots):
        slots[c // 2] = (slots[c // 2][0], slots[c // 2][1], True)

    lines = [_header("W-chaos", seed, scale,
                     "rounds=%d C=%d" % (rounds, c))]
    lines.append("import str\n")

    lines.append("""\
fn build(n, acc) {
  if n == 0 {
    acc
  } else {
    build(n - 1, cons(n, acc))
  }
}

// leaf: first message = [alloc_n, sub, die]; dies by crash or returns
fn leaf() {
  let cfg = recv()
  let n = car(cfg)
  let sub = car(cdr(cfg))
  let die = car(cdr(cdr(cfg)))
  let junk = build(n, nil)
  if die {
    let z = n - n
    let boom = n / z
    0
  } else {
    if sub {
      let child = spawn('leaf)
      let ref = monitor(child)
      send(child, [1, false, false])
      let down2 = recv()
      junk
    } else {
      junk
    }
  }
}
""")

    lines.append("""\
fn wait_downs(i, c) {
  if i == c {
    0
  } else {
    let down = recv()
    wait_downs(i + 1, c)
  }
}

fn spawn_leaves(r, rounds, c, j, tbl) {
  if j == c {
    wait_downs(0, c)
    print(str.concat("round ", str.from_int(r)))
    rounds_loop(r + 1, rounds, c, tbl)
  } else {
    let pid = spawn('leaf)
    let ref = monitor(pid)
    send(pid, nth(tbl, j))
    spawn_leaves(r, rounds, c, j + 1, tbl)
  }
}

fn rounds_loop(r, rounds, c, tbl) {
  if r == rounds {
    print(str.concat("done ", str.from_int(r)))
  } else {
    spawn_leaves(r, rounds, c, 0, tbl)
  }
}
""")

    def lit_bool(b):
        return "true" if b else "false"

    slot_lits = ["[%d, %s, %s]"
                 % (n, lit_bool(s), lit_bool(d)) for (n, s, d) in slots]
    tbl = "[" + ", ".join(slot_lits) + "]"
    lines.append("fn nth(lst, n) {")
    lines.append("  if n == 0 {")
    lines.append("    car(lst)")
    lines.append("  } else {")
    lines.append("    nth(cdr(lst), n - 1)")
    lines.append("  }")
    lines.append("}\n")
    lines.append("fn main() {")
    lines.append("  rounds_loop(0, %d, %d, %s)" % (rounds, c, tbl))
    lines.append("}\n")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# dispatch / CLI / smoke
# ---------------------------------------------------------------------------

_GENERATORS = {
    "pure": gen_pure,
    "msg": gen_msg,
    "chaos": gen_chaos,
}


def generate(kind, seed, scale=1):
    """Generate one workload's .ta source (deterministic in all args)."""
    if kind not in _GENERATORS:
        raise ValueError("kind must be one of %s, got %r"
                         % ("/".join(KINDS), kind))
    if not (0 <= seed < (1 << 64)):
        raise ValueError("seed must be in [0, 2^64)")
    return _GENERATORS[kind](seed, _check_scale(scale))


def run_smoke(text, timeout=300):
    """Build+run `text` via ./tinyactor; return (returncode, stdout, stderr).

    Skips (returns None) when ./tinyactor is not built so the unit test
    suite degrades gracefully on a bare checkout.
    """
    if not os.path.exists(TINYACTOR):
        return None
    with tempfile.NamedTemporaryFile(
            "w", suffix=".ta", delete=False) as f:
        f.write(text)
        path = f.name
    try:
        proc = subprocess.run(
            [TINYACTOR, "run", path],
            capture_output=True, timeout=timeout)
        return proc.returncode, proc.stdout, proc.stderr
    finally:
        os.unlink(path)


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Generate a GC-hostile TA workload "
                    "(docs/kernel-fuzzing-design.md §7.0-7.4)")
    ap.add_argument("--kind", required=True, choices=KINDS,
                    help="pure: sequential diff / msg: multiset harness / "
                         "chaos: TSan long-run")
    ap.add_argument("--seed", required=True, type=int,
                    help="PRNG seed (u64, M-2 counter-based sha256 stream)")
    ap.add_argument("--scale", type=int, default=1,
                    help="allocation/scale multiplier (>= 1)")
    ap.add_argument("--smoke", action="store_true",
                    help="after generating, build+run via ./tinyactor and "
                         "exit nonzero on failure (generator self-check)")
    args = ap.parse_args(argv)

    text = generate(args.kind, args.seed, args.scale)
    if args.smoke:
        res = run_smoke(text)
        if res is None:
            print("gc-workloads-SKIPPED: ./tinyactor not built", file=sys.stderr)
            return 0
        rc, out, err = res
        ok = rc == 0 and len(out) > 0
        if not ok:
            sys.stdout.write(text)
            print("gc-workloads-SMOKE-FAIL: rc=%d stdout=%dB stderr=%s"
                  % (rc, len(out), err.decode("utf-8", "replace")[:2000]),
                  file=sys.stderr)
            return 1
        print("gc-workloads-SMOKE-OK: kind=%s seed=%d scale=%d rc=0 stdout=%dB"
              % (args.kind, args.seed, args.scale, len(out)), file=sys.stderr)
        return 0
    sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())