#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""multiset.py — W-msg message-multiset conservation harness (DELIV-8b).

Task: .pge/tasks/task-multiset.md; authoritative design:
docs/kernel-fuzzing-design.md §7.3 (concurrent multiset harness) + §7.0
(W-msg -> multiset conservation row of the workload x oracle matrix).
Python3 stdlib only (DEC-6).

Shape (§7.3): a K-worker x M-message TA driver is generated per seed; every
worker sends its collector M messages tagged "<wid> <seq>"; the collector
prints one line per message and returns.  ALL sorting/diffing happens here in
Python — the TA program stays minimal (never sorts), per §7.3.

Verdict per case:
  * collected lines sorted == expected enumeration (K*M cartesian product,
    "<wid> <seq>" for wid in [0,K) x seq in [0,M))  -> conserved (exit 0)
  * well-formed line missing                       -> "dropped" (lost message)
  * well-formed line not in expected (or duplicated)-> "extra"
  * line not matching ^\\d+ \\d+$                    -> "malformed"
  * no exit within --timeout (default 10s)         -> "timeout"; the partial
    output is still judged, so a timeout case usually also reports "dropped"
    (丢消息与死锁二选一均报, §7.3).

First-day semantics verification (§7.3 首日核实, probed 2026-09-04 against
the working-tree VM, probes in /tmp/msprobe during task-multiset):
  * collector "函数返回即进程正常死亡" CONFIRMED: a collector that returns
    normally (no explicit HALT — the language has no halt form in the spec)
    terminates its process; a monitor on it receives DOWN and the main
    process's recv() unblocks; program exits 0 (probe p1.ta, K=2 M=3,
    exactly 6 lines + exit 0).
  * recv() on an empty mailbox BLOCKS (probe p5.ta: a spawned worker that
    recvs first never reaches its print while main spins).
  * HOWEVER the VM reaps an all-blocked process set with exit 0 (probe
    p4.ta: main waiting on monitor DOWN + worker blocked on recv -> immediate
    exit 0).  Consequence for classification: a lost-message deadlock does
    NOT surface as "timeout" — it exits 0 with missing lines ("dropped").
    "timeout" only fires on live (spinning/livelock) processes; the unit
    test therefore uses an infinite tail-recursive spin program.
  * The generated driver below is the hand-probed p1.ta text with only two
    seed-varied knobs: worker spawn ORDER (seeded Fisher-Yates) and per-
    worker payload length.  Structure identical to gc_workloads.gen_msg
    (zero-arg spawn + first-message config, R3).

Findings: one JSON per novel finding under .pge/findings/multiset/
(seed/K/M + categories + counts + signature), the triggering .ta saved
alongside.  Signature = sha256 over (categories, k, m, per-category counts)
— family-level dedup: two runs losing a different 3-of-25 lines under the
same K/M collapse to one signature by design (scheduler nondeterminism makes
line-identity dedup useless); identical signatures already on disk are
counted as "known" and not rewritten.

CLI:
    python3 tools/kernfuzz/multiset.py --seeds 0:5 --k 2 --m 10
Exit code: 0 = every case conserved (and no new findings); 1 = any finding
(novel or known).
"""

import argparse
import concurrent.futures
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
import time

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

import prng                      # noqa: E402

_REPO = os.path.normpath(os.path.join(_HERE, "..", ".."))
TINYACTOR = os.path.join(_REPO, "tinyactor")
DEFAULT_FINDINGS_DIR = os.path.join(_REPO, ".pge", "findings", "multiset")

DEFAULT_TIMEOUT = 10.0           # §7.3: 超时（10s）= finding

# "<wid> <seq>", decimal, no leading/trailing junk
LINE_RE = re.compile(r"^(\d+) (\d+)$")

MAX_TOTAL = 1 << 20              # sanity cap on K*M


# ---------------------------------------------------------------------------
# TA driver generation (§7.3 skeleton, K/M parameterized)
# ---------------------------------------------------------------------------

def gen_driver(seed, k, m):
    """Emit the W-msg multiset driver for (seed, k, m) as a .ta source string.

    Deterministic in all three arguments.  Output contract: exactly k*m
    lines "<wid> <seq>" on stdout (any order), exit 0.
    """
    _check_km(k, m)
    p = prng.make_prng(seed)

    # seed-varied worker spawn order (Fisher-Yates over the PRNG stream)
    order = list(range(k))
    for i in range(k - 1, 0, -1):
        j = p.next_range(i + 1)
        order[i], order[j] = order[j], order[i]
    # seed-varied per-worker payload length (deep-list churn across send)
    plens = [8 + p.next_range(17) for _ in range(k)]

    lines = ["// multiset harness seed=%d K=%d M=%d order=%s plens=%s"
             % (seed, k, m, order, plens),
             "// generated by tools/kernfuzz/multiset.py — do not edit",
             "import str",
             "",
             "fn collect_loop(i, n) {",
             "  if i == n {",
             "    0",
             "  } else {",
             "    let msg = recv()",
             "    print(str.concat(str.from_int(car(msg)), "
             "str.concat(\" \", str.from_int(car(cdr(msg))))))",
             "    collect_loop(i + 1, n)",
             "  }",
             "}",
             "",
             "// first message = [total]; drain total messages, print one",
             "// \"<wid> <seq>\" line each (no sorting in TA, §7.3), return",
             "fn collector() {",
             "  let cfg = recv()",
             "  collect_loop(0, car(cfg))",
             "}",
             "",
             "// fresh deep payload per message: send deep-copies it,",
             "// collector drops it (§7.0 W-msg shape)",
             "fn payload(n, acc) {",
             "  if n == 0 {",
             "    acc",
             "  } else {",
             "    payload(n - 1, cons(n, acc))",
             "  }",
             "}",
             "",
             "fn wloop(cp, wid, s, m, plen) {",
             "  if s == m {",
             "    0",
             "  } else {",
             "    send(cp, cons(wid, cons(s, payload(plen, nil))))",
             "    wloop(cp, wid, s + 1, m, plen)",
             "  }",
             "}",
             "",
             "// first message = [cp, wid, m, plen] (spawn is zero-arg, R3)",
             "fn worker() {",
             "  let cfg = recv()",
             "  wloop(car(cfg), car(cdr(cfg)), 0, "
             "car(cdr(cdr(cfg))), car(cdr(cdr(cdr(cfg)))))",
             "}",
             "",
             "fn main() {",
             "  let cp = spawn('collector)",
             "  send(cp, cons(%d, nil))" % (k * m)]
    for wid in order:
        lines.append("  let w%d = spawn('worker)" % wid)
        lines.append("  send(w%d, cons(cp, cons(%d, cons(%d, cons(%d, nil)))))"
                     % (wid, wid, m, plens[wid]))
    lines += ["  let ref = monitor(cp)",
              "  recv()",
              "}",
              ""]
    return "\n".join(lines)


def _check_km(k, m):
    if not (isinstance(k, int) and isinstance(m, int)):
        raise TypeError("k and m must be ints")
    if k < 1 or m < 1:
        raise ValueError("k and m must be >= 1")
    if k > 1024 or m > 1024:
        raise ValueError("k and m must be <= 1024")
    if k * m > MAX_TOTAL:
        raise ValueError("k*m must be <= %d" % MAX_TOTAL)
    return k, m


def expected_multiset(k, m):
    """Expected output: sorted list of the K*M "<wid> <seq>" lines."""
    _check_km(k, m)
    return sorted("%d %d" % (w, s) for w in range(k) for s in range(m))


# ---------------------------------------------------------------------------
# Judge: pure classification over collected lines (unit-testable, no I/O)
# ---------------------------------------------------------------------------

def judge(lines, expected):
    """Classify collected stdout `lines` against sorted `expected` lines.

    Returns a verdict dict:
      conserved   bool — True iff no dropped/extra/malformed at all
      malformed   list of offending raw lines (order of appearance)
      dropped     sorted list of expected lines never seen
      extra       sorted list of well-formed lines not in expected
                  (duplicates count as extra)
    Pure function: no I/O, no clock — direct fake-stdout feed is the
    targeted judge validation (task acceptance #3).
    """
    malformed = [ln for ln in lines if not LINE_RE.match(ln)]
    got = {}
    for ln in lines:
        mt = LINE_RE.match(ln)
        if mt:
            got[ln] = got.get(ln, 0) + 1
    exp = {}
    for ln in expected:
        exp[ln] = exp.get(ln, 0) + 1
    dropped = sorted(ln for ln in exp if got.get(ln, 0) < exp[ln])
    extra = sorted(ln for ln, n in got.items()
                   if n > exp.get(ln, 0) for _ in range(n - exp.get(ln, 0)))
    return {
        "conserved": not (malformed or dropped or extra),
        "malformed": malformed,
        "dropped": dropped,
        "extra": extra,
    }


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------

def run_program(source, expected, timeout=DEFAULT_TIMEOUT,
                tinyactor=TINYACTOR):
    """Build+run `source` via tinyactor, judge stdout against `expected`.

    Returns a case dict; never raises for program-level failures (compile
    error / nonzero exit / timeout all become findings).
    """
    t0 = time.time()
    fd, path = tempfile.mkstemp(suffix=".ta", prefix="ms-")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(source)
        timed_out = False
        stdout, rc = b"", None
        try:
            proc = subprocess.run([tinyactor, "run", path],
                                  capture_output=True, timeout=timeout)
            stdout, rc = proc.stdout, proc.returncode
        except subprocess.TimeoutExpired as exc:
            timed_out = True
            stdout = exc.stdout or b""
            rc = None
    finally:
        os.unlink(path)
    duration = time.time() - t0
    text = stdout.decode("utf-8", "replace")
    out_lines = [ln for ln in text.splitlines()
                 if ln.strip()]  # ignore blank lines, judge the rest
    v = judge(out_lines, expected)
    categories = []
    if timed_out:
        categories.append("timeout")
    for cat in ("malformed", "dropped", "extra"):
        if v[cat]:
            categories.append(cat)
    return {
        "conserved": v["conserved"] and not timed_out,
        "timed_out": timed_out,
        "rc": rc,
        "duration": duration,
        "n_lines": len(out_lines),
        "verdict": v,
        "categories": categories,
        "source": source,
        "stdout": text,
    }


def run_case(seed, k, m, timeout=DEFAULT_TIMEOUT, tinyactor=TINYACTOR):
    """One harness case: generate driver for (seed, k, m) and run it."""
    return run_program(gen_driver(seed, k, m), expected_multiset(k, m),
                       timeout=timeout, tinyactor=tinyactor)


# ---------------------------------------------------------------------------
# Findings: signature dedup + JSON evidence under .pge/findings/multiset/
# ---------------------------------------------------------------------------

def signature(case, k, m):
    """Family-level dedup signature (see module docstring)."""
    v = case["verdict"]
    parts = ["multiset", ",".join(sorted(case["categories"])),
             "k=%d" % k, "m=%d" % m,
             "malformed=%d" % len(v["malformed"]),
             "dropped=%d" % len(v["dropped"]),
             "extra=%d" % len(v["extra"]),
             "rc=%s" % case["rc"]]
    return hashlib.sha256("|".join(parts).encode()).hexdigest()


def record_finding(case, seed, k, m, findings_dir):
    """Write finding JSON + triggering source unless signature already known.

    Returns "novel" or "known".
    """
    sig = signature(case, k, m)
    os.makedirs(findings_dir, exist_ok=True)
    jpath = os.path.join(findings_dir, sig + ".json")
    if os.path.exists(jpath):
        return "known"
    v = case["verdict"]
    doc = {
        "tool": "multiset",
        "signature": sig,
        "seed": seed,
        "k": k,
        "m": m,
        "categories": sorted(case["categories"]),
        "rc": case["rc"],
        "timed_out": case["timed_out"],
        "duration_s": round(case["duration"], 3),
        "n_lines": case["n_lines"],
        "n_malformed": len(v["malformed"]),
        "n_dropped": len(v["dropped"]),
        "n_extra": len(v["extra"]),
        "malformed_sample": v["malformed"][:5],
        "dropped_sample": v["dropped"][:5],
        "extra_sample": v["extra"][:5],
        "stdout_tail": case["stdout"][-500:],
    }
    tmp = jpath + ".tmp"
    with open(tmp, "w") as f:
        json.dump(doc, f, indent=2, sort_keys=True)
        f.write("\n")
    os.replace(tmp, jpath)
    with open(os.path.join(findings_dir, sig + ".ta"), "w") as f:
        f.write(case["source"])
    return "novel"


# ---------------------------------------------------------------------------
# Matrix driver
# ---------------------------------------------------------------------------

def run_matrix(seeds, ks, ms, jobs=None, timeout=DEFAULT_TIMEOUT,
               tinyactor=TINYACTOR, findings_dir=DEFAULT_FINDINGS_DIR):
    """Run seeds x ks x ms cases in parallel; return a summary dict."""
    if jobs is None:
        jobs = min(8, os.cpu_count() or 1)
    combos = [(s, k, m) for s in seeds for k in ks for m in ms]
    t0 = time.time()
    results = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=jobs) as ex:
        futs = {ex.submit(run_case, s, k, m, timeout, tinyactor): (s, k, m)
                for (s, k, m) in combos}
        for fut in concurrent.futures.as_completed(futs):
            results[futs[fut]] = fut.result()

    summary = {
        "n_cases": len(combos),
        "conserved": 0,
        "findings": [],
        "n_findings": 0,
        "n_known": 0,
        "timeout": timeout,
        "jobs": jobs,
        "elapsed_s": 0.0,
    }
    for (s, k, m) in sorted(combos):
        case = results[(s, k, m)]
        if case["conserved"]:
            summary["conserved"] += 1
            continue
        status = record_finding(case, s, k, m, findings_dir)
        if status == "novel":
            summary["n_findings"] += 1
        else:
            summary["n_known"] += 1
        summary["findings"].append({
            "seed": s, "k": k, "m": m,
            "categories": sorted(case["categories"]),
            "signature": signature(case, k, m),
            "status": status,
        })
    summary["elapsed_s"] = round(time.time() - t0, 2)
    return summary


def print_summary(summary, stream=sys.stderr):
    """One-line-per-finding tally + verdict (matches kernfuzz/fast.py style)."""
    per_cat = {}
    for f in summary["findings"]:
        for c in f["categories"]:
            per_cat[c] = per_cat.get(c, 0) + 1
    print("multiset: cases=%d conserved=%d findings=%d known=%d "
          "{%s} timeout=%ss jobs=%d elapsed=%.1fs"
          % (summary["n_cases"], summary["conserved"],
             summary["n_findings"], summary["n_known"],
             " ".join("%s=%d" % kv for kv in sorted(per_cat.items())) or "-",
             summary["timeout"], summary["jobs"], summary["elapsed_s"]),
          file=stream)
    for f in summary["findings"]:
        print("  FINDING seed=%d K=%d M=%d %s [%s]"
              % (f["seed"], f["k"], f["m"], f["status"],
                 ",".join(f["categories"])), file=stream)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_int_list(text, name):
    try:
        vals = [int(x) for x in text.split(",")]
    except ValueError:
        raise SystemExit("%s must be a comma list of ints, got %r"
                         % (name, text))
    if not vals:
        raise SystemExit("%s must not be empty" % name)
    return vals


def _parse_seeds(text):
    try:
        a, b = text.split(":", 1)
        a, b = int(a), int(b)
    except ValueError:
        raise SystemExit("--seeds must be A:B (half-open range), got %r"
                         % text)
    if b <= a:
        raise SystemExit("--seeds needs A < B, got %r" % text)
    return range(a, b)


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="W-msg message-multiset conservation harness "
                    "(docs/kernel-fuzzing-design.md §7.3)")
    ap.add_argument("--seeds", required=True, metavar="A:B",
                    help="half-open seed range A..B-1")
    ap.add_argument("--k", default="4", metavar="K[,K...]",
                    help="worker count(s), comma list (default 4)")
    ap.add_argument("--m", default="25", metavar="M[,M...]",
                    help="messages per worker, comma list (default 25)")
    ap.add_argument("--jobs", type=int, default=None, metavar="J",
                    help="parallel cases (default min(8, cpus))")
    ap.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT,
                    help="per-case timeout seconds (default 10)")
    ap.add_argument("--tinyactor", default=TINYACTOR, metavar="PATH",
                    help="binary under test (default repo ./tinyactor)")
    ap.add_argument("--findings-dir", default=DEFAULT_FINDINGS_DIR,
                    metavar="DIR", help="finding evidence directory")
    args = ap.parse_args(argv)

    seeds = _parse_seeds(args.seeds)
    ks = _parse_int_list(args.k, "--k")
    ms = _parse_int_list(args.m, "--m")
    for k in ks:
        for m in ms:
            _check_km(k, m)

    summary = run_matrix(seeds, ks, ms, jobs=args.jobs,
                         timeout=args.timeout, tinyactor=args.tinyactor,
                         findings_dir=args.findings_dir)
    print_summary(summary)
    if args.findings_dir == DEFAULT_FINDINGS_DIR:
        print("findings dir: %s" % args.findings_dir, file=sys.stderr)
    return 0 if summary["n_cases"] == summary["conserved"] else 1


if __name__ == "__main__":
    sys.exit(main())