#!/usr/bin/env bash
#
# build-wasm.sh — Reproducible Emscripten build of the TinyActor VM (wasm).
#
# Produces docs/wasm/tinyactor-vm.js + docs/wasm/tinyactor-vm.wasm for the
# Playground page (browser-side compile + run of TA code):
#
#   * C VM (src/*.c) compiled to wasm by emcc with zero source changes.
#   * Virtual FS payload embedded into the wasm:
#       - lib/bootstrap.tabc                         — TA bootstrap compiler bytecode
#       - lib/{tokenizer,parser,codegen,typecheck,fmt}.ta
#                                                    — compiler TA modules (needed for
#                                                      runtime import resolution)
#       - hello.ta / hello.tabc                       — sample program (print(1 + 41) → 42)
#   * MODULARIZE + callMain/FS exports — the JS bridge used by the Playground:
#         mod.callMain(['lib/bootstrap.tabc','user.ta','user.tabc'])  // compile
#         mod.callMain(['user.tabc'])                                  // run
#
# All intermediate artifacts go to a temp dir (cleaned up on exit); the only
# repository output is docs/wasm/. The script is idempotent and repeatable.
#
# Usage:
#   scripts/build-wasm.sh [options]
#     -v | --verbose    print every command + payload details
#     --no-verify       skip the node closure checks (build only)
#     -h | --help       show this help
#
# Requires: emcc (Emscripten), node, cc.
#
set -euo pipefail

VERBOSE=0
VERIFY=1

usage() {
    sed -n '2,25p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

for arg in "$@"; do
    case "$arg" in
        -v|--verbose) VERBOSE=1 ;;
        --no-verify) VERIFY=0 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "build-wasm.sh: unknown option: $arg" >&2; usage >&2; exit 1 ;;
    esac
done

# --- Paths ---------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$REPO_ROOT/docs/wasm"
TMP="$(mktemp -d "${TMPDIR:-/tmp}/tavm-wasm.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

log()  { printf '[build-wasm] %s\n' "$*"; }
run() {
    if [ "$VERBOSE" -eq 1 ]; then printf '+ %s\n' "$*" >&2; fi
    "$@"
}

# --- Toolchain checks ----------------------------------------------------
command -v emcc >/dev/null 2>&1 || { echo "build-wasm.sh: emcc not found (brew install emscripten)" >&2; exit 1; }
command -v cc   >/dev/null 2>&1 || { echo "build-wasm.sh: cc not found (needed to precompile hello.tabc)" >&2; exit 1; }
if [ "$VERIFY" -eq 1 ]; then
    command -v node >/dev/null 2>&1 || { echo "build-wasm.sh: node not found (needed for --verify)" >&2; exit 1; }
fi

log "repo root: $REPO_ROOT"
log "emcc:      $(emcc --version 2>/dev/null | head -1)"

# --- 1. Collect C sources (main repo files, copied to temp) --------------
mkdir -p "$TMP/src"
cp "$REPO_ROOT"/src/*.c "$REPO_ROOT/ta.h" "$REPO_ROOT/ta_inline.h" "$TMP/src/"

# --- 2. Temp native tavm to precompile hello.tabc ------------------------
# hello.tabc is generated by the real bootstrap compiler (lib/bootstrap.tabc)
# with a throwaway native build of the VM — no repo artifacts are touched.
log "building temp native tavm (hello.tabc generation)"
NATIVE_CC=(cc -Wall -Wextra -std=c99 -O2 -I"$TMP/src" "$TMP"/src/*.c)
if [ "$(uname -s)" = "Linux" ]; then NATIVE_CC+=(-ldl); fi
run "${NATIVE_CC[@]}" -o "$TMP/tavm-native" -lpthread

# --- 3. Embedded payload --------------------------------------------------
# lib/: bootstrap compiler bytecode + the TA compiler modules the driver
# resolves at compile time (driver.ta falls back to lib/<name>.ta for
# `import <name>` in user code).
mkdir -p "$TMP/payload/lib"
cp "$REPO_ROOT/lib/bootstrap.tabc" \
   "$REPO_ROOT/lib/tokenizer.ta" "$REPO_ROOT/lib/parser.ta" \
   "$REPO_ROOT/lib/codegen.ta" "$REPO_ROOT/lib/typecheck.ta" \
   "$REPO_ROOT/lib/fmt.ta" \
   "$TMP/payload/lib/"

# Sample program (golden: print(1 + 41) → 42).
cat > "$TMP/payload/hello.ta" <<'EOF'
fn main() {
  print(1 + 41)
}
EOF

# Precompile the sample with the real compiler so the wasm can run it
# standalone (minimal closure) without a separate compile step.
( cd "$TMP/payload" && "$TMP/tavm-native" lib/bootstrap.tabc hello.ta hello.tabc )

if [ "$VERBOSE" -eq 1 ]; then
    log "payload:"
    ( cd "$TMP/payload" && du -ah hello.ta hello.tabc lib/* | sort -k2 )
fi

# --- 4. Emscripten build ---------------------------------------------------
# `--embed-file lib` etc. are relative to the payload dir so the embedded
# virtual FS paths are /lib/... , /hello.ta , /hello.tabc.
log "emcc build -> $OUT_DIR"
mkdir -p "$TMP/out" "$OUT_DIR"
EMCC_FLAGS=(
    -Wall -Wextra -std=c99 -O2
    -I"$TMP/src" "$TMP"/src/*.c
    --embed-file lib
    --embed-file hello.ta
        --embed-file hello.tabc
    -s MODULARIZE
    -s EXPORT_NAME=createTavm
    -s EXPORTED_RUNTIME_METHODS=callMain,FS
    # Do not auto-run main() at module load: the Playground drives the VM
    # explicitly via callMain/FS after createTavm({noInitialRun:true}).
    -s INVOKE_RUN=0
)
run bash -c 'cd "$1" && shift && emcc "$@"' _ "$TMP/payload" "${EMCC_FLAGS[@]}" -o "$TMP/out/tinyactor-vm.js"

cp "$TMP/out/tinyactor-vm.js" "$TMP/out/tinyactor-vm.wasm" "$OUT_DIR/"

JS_SIZE="$(stat -f%z "$OUT_DIR/tinyactor-vm.js" 2>/dev/null || stat -c%s "$OUT_DIR/tinyactor-vm.js")"
WASM_SIZE="$(stat -f%z "$OUT_DIR/tinyactor-vm.wasm" 2>/dev/null || stat -c%s "$OUT_DIR/tinyactor-vm.wasm")"
log "artifacts: docs/wasm/tinyactor-vm.js ($JS_SIZE B), tinyactor-vm.wasm ($WASM_SIZE B)"

# --- 5. Closure verification (node) ---------------------------------------
if [ "$VERIFY" -eq 1 ]; then
    cat > "$TMP/verify.js" <<'EOF'
// Closure checks for docs/wasm/tinyactor-vm.js
const assert = require('node:assert');
const createTavm = require('TMPOUT/tinyactor-vm.js');

async function makeModule() {
  const lines = [];
  const mod = await createTavm({
    noInitialRun: true,          // no auto-run of main() at load
    print: (s) => lines.push(String(s)),
  });
  return { mod, lines };
}

async function main() {
  // Closure 1 (minimal): run the embedded hello.tabc -> 42
  {
    const { mod, lines } = await makeModule();
    const rc = mod.callMain(['hello.tabc']);
    assert.strictEqual(rc, 0, 'minimal run exit code');
    assert.ok(lines.includes('42'), 'minimal run stdout should contain 42, got: ' + JSON.stringify(lines));
    console.log('PASS minimal: hello.tabc ->', JSON.stringify(lines));
  }
  // Closure 2 (full): compile hello.ta -> hello-out.tabc inside wasm, then run -> 42
  {
    const { mod, lines } = await makeModule();
    const rc = mod.callMain(['lib/bootstrap.tabc', 'hello.ta', 'hello-out.tabc']);
    assert.strictEqual(rc, 0, 'compile exit code');
    const bytes = mod.FS.readFile('hello-out.tabc');
    assert.ok(bytes.length > 0, 'compiled bytecode should be non-empty');
    lines.length = 0;
    const rc2 = mod.callMain(['hello-out.tabc']);
    assert.strictEqual(rc2, 0, 'run exit code');
    assert.ok(lines.includes('42'), 'compiled run stdout should contain 42, got: ' + JSON.stringify(lines));
    console.log('PASS full: hello.ta -> hello-out.tabc (' + bytes.length + 'B) ->', JSON.stringify(lines));
  }
  console.log('ALL VERIFICATIONS PASSED');
  process.exit(0);
}

main().catch((e) => { console.error('VERIFY FAILED:', e); process.exit(1); });
EOF
    sed -i.bak "s|TMPOUT|$TMP/out|" "$TMP/verify.js" && rm -f "$TMP/verify.js.bak"
    log "verifying closures with node"
    node "$TMP/verify.js"
fi

log "done. artifacts in docs/wasm/"